INSERT INTO Amenities VALUES(1, 'Hot Water');
INSERT INTO Amenities VALUES(2, 'Washer');
INSERT INTO Amenities VALUES(3, 'Dryer');
INSERT INTO Amenities VALUES(4, 'Hangers');
INSERT INTO Amenities VALUES(5, 'Bed Sheets');
INSERT INTO Amenities VALUES(6, 'TV');
INSERT INTO Amenities VALUES(7, 'Air Conditioning');
INSERT INTO Amenities VALUES(8, 'Heating');
INSERT INTO Amenities VALUES(9, 'Indoor Fireplace');
INSERT INTO Amenities VALUES(10, 'Security Cameras');
INSERT INTO Amenities VALUES(11, 'Smoke Alarm');
INSERT INTO Amenities VALUES(12, 'Free Wifi');
INSERT INTO Amenities VALUES(13, 'Paid Wifi');
INSERT INTO Amenities VALUES(14, 'Free Parking');
INSERT INTO Amenities VALUES(15, 'Garage');
INSERT INTO Amenities VALUES(16, 'Lawn');
INSERT INTO Amenities VALUES(17, 'Kitchen');
INSERT INTO Amenities VALUES(18, 'Microwave');
INSERT INTO Amenities VALUES(19, 'Cooking Utensils');
INSERT INTO Amenities VALUES(20, 'Dishwasher');
INSERT INTO Amenities VALUES(21, 'Stove');
INSERT INTO Amenities VALUES(22, 'Oven');
INSERT INTO Amenities VALUES(23, 'Toaster');
INSERT INTO Amenities VALUES(24, 'Refrigerator');
INSERT INTO Amenities VALUES(25, 'Barbeque Grill');
INSERT INTO Amenities VALUES(26, 'Patio');
INSERT INTO Amenities VALUES(27, 'Balcony');
INSERT INTO Amenities VALUES(28, 'Hot Tub');
INSERT INTO Amenities VALUES(29, 'Swimming Pool');
INSERT INTO Amenities VALUES(30, 'Sauna');