INSERT INTO IsIn VALUES(1, 1);  -- Scarborough
INSERT INTO IsIn VALUES(2, 1);  
INSERT INTO IsIn VALUES(3, 1);  
INSERT INTO IsIn VALUES(4, 1);  
INSERT INTO IsIn VALUES(5, 1);  
INSERT INTO IsIn VALUES(6, 1);  
INSERT INTO IsIn VALUES(7, 1);  
INSERT INTO IsIn VALUES(8, 1);  
INSERT INTO IsIn VALUES(9, 1);  
INSERT INTO IsIn VALUES(10, 1);  
INSERT INTO IsIn VALUES(11, 1);  
INSERT INTO IsIn VALUES(12, 1);  
INSERT INTO IsIn VALUES(13, 1);  
INSERT INTO IsIn VALUES(14, 1);   -- Scarborough
INSERT INTO IsIn VALUES(15, 1);  --  North York
INSERT INTO IsIn VALUES(16, 1);  
INSERT INTO IsIn VALUES(17, 1);  
INSERT INTO IsIn VALUES(18, 1);  
INSERT INTO IsIn VALUES(19, 1); 
INSERT INTO IsIn VALUES(20, 1); 
INSERT INTO IsIn VALUES(21, 1); 
INSERT INTO IsIn VALUES(22, 1); 
INSERT INTO IsIn VALUES(23, 1); 
INSERT INTO IsIn VALUES(24, 1); 
INSERT INTO IsIn VALUES(25, 1);  
INSERT INTO IsIn VALUES(26, 1); 
INSERT INTO IsIn VALUES(27, 1);  --  North York
INSERT INTO IsIn VALUES(28, 1);  -- Toronto
INSERT INTO IsIn VALUES(29, 1);  
INSERT INTO IsIn VALUES(30, 1); 
INSERT INTO IsIn VALUES(31, 1);  
INSERT INTO IsIn VALUES(32, 1); 
INSERT INTO IsIn VALUES(33, 1); 
INSERT INTO IsIn VALUES(34, 1);  
INSERT INTO IsIn VALUES(35, 1); 
INSERT INTO IsIn VALUES(36, 1);  
INSERT INTO IsIn VALUES(37, 1);  
INSERT INTO IsIn VALUES(38, 1);  
INSERT INTO IsIn VALUES(39, 1);  
INSERT INTO IsIn VALUES(40, 1);   -- Toronto
INSERT INTO IsIn VALUES(41, 3);  -- Mississauga
INSERT INTO IsIn VALUES(42, 3);  
INSERT INTO IsIn VALUES(43, 3);  
INSERT INTO IsIn VALUES(44, 3);  
INSERT INTO IsIn VALUES(45, 3);  
INSERT INTO IsIn VALUES(46, 3);  
INSERT INTO IsIn VALUES(47, 3);  
INSERT INTO IsIn VALUES(48, 3);  
INSERT INTO IsIn VALUES(49, 3);  
INSERT INTO IsIn VALUES(50, 3);  
INSERT INTO IsIn VALUES(51, 3);  
INSERT INTO IsIn VALUES(52, 3);  
INSERT INTO IsIn VALUES(53, 3);  
INSERT INTO IsIn VALUES(54, 3);  
INSERT INTO IsIn VALUES(55, 3);  -- Mississauga
INSERT INTO IsIn VALUES(56, 2);   -- Markham
INSERT INTO IsIn VALUES(57, 2);  
INSERT INTO IsIn VALUES(58, 2);  
INSERT INTO IsIn VALUES(59, 2);  
INSERT INTO IsIn VALUES(60, 2);  
INSERT INTO IsIn VALUES(61, 2); 
INSERT INTO IsIn VALUES(62, 2);   -- Markham
INSERT INTO IsIn VALUES(63, 4);   -- Richmond Hill
INSERT INTO IsIn VALUES(64, 4);  
INSERT INTO IsIn VALUES(65, 4);  
INSERT INTO IsIn VALUES(66, 4);  
INSERT INTO IsIn VALUES(67, 4);  
INSERT INTO IsIn VALUES(68, 4);
INSERT INTO IsIn VALUES(69, 4); 
INSERT INTO IsIn VALUES(70, 4);
INSERT INTO IsIn VALUES(71, 4); 
INSERT INTO IsIn VALUES(72, 4);  
INSERT INTO IsIn VALUES(73, 4); -- Richmond Hill