INSERT INTO IsIn VALUES('M1S 4B5', 1);  -- Scarborough
INSERT INTO IsIn VALUES('M1B 2V9', 1);  
INSERT INTO IsIn VALUES('M1G 3S3', 1);  
INSERT INTO IsIn VALUES('M1C 0C7', 1);  
INSERT INTO IsIn VALUES('M1E 4B8', 1);  
INSERT INTO IsIn VALUES('M1E 4B9', 1);  
INSERT INTO IsIn VALUES('M1H 2Y6', 1);  
INSERT INTO IsIn VALUES('M1P 4P5', 1);  
INSERT INTO IsIn VALUES('M1P 2Y3', 1);  
INSERT INTO IsIn VALUES('M1P 4W2', 1);  
INSERT INTO IsIn VALUES('M1P 4R4', 1);  
INSERT INTO IsIn VALUES('M1H 1A8', 1);  
INSERT INTO IsIn VALUES('M1H 1A9', 1);  
INSERT INTO IsIn VALUES('M1B 6A3', 1);   -- Scarborough
INSERT INTO IsIn VALUES('M2J 5A7', 1);  --  North York
INSERT INTO IsIn VALUES('M2N 3B3', 1);  
INSERT INTO IsIn VALUES('M2N 5X2', 1);  
INSERT INTO IsIn VALUES('M2N 6G5', 1);  
INSERT INTO IsIn VALUES('M2N 5M2', 1); 
INSERT INTO IsIn VALUES('M2N 7G9', 1); 
INSERT INTO IsIn VALUES('M2N 6Z4', 1); 
INSERT INTO IsIn VALUES('M2N 5R6', 1); 
INSERT INTO IsIn VALUES('M2G 5S4', 1); 
INSERT INTO IsIn VALUES('M2N 3T9', 1); 
INSERT INTO IsIn VALUES('M5H 2M5', 1);  
INSERT INTO IsIn VALUES('M2P 2B7', 1); 
INSERT INTO IsIn VALUES('M2P 2E3', 1);  --  North York
INSERT INTO IsIn VALUES('M5G 2C4', 1);  -- Toronto
INSERT INTO IsIn VALUES('M1C 3T8', 1);  
INSERT INTO IsIn VALUES('M5S 1A1', 1); 
INSERT INTO IsIn VALUES('M5B 2H4', 1);  
INSERT INTO IsIn VALUES('M5A 1Z4', 1); 
INSERT INTO IsIn VALUES('M5C 3G7', 1); 
INSERT INTO IsIn VALUES('M5A 4R3', 1);  
INSERT INTO IsIn VALUES('M5E 1B5', 1); 
INSERT INTO IsIn VALUES('M5E 1G4', 1);  
INSERT INTO IsIn VALUES('M5V 2L1', 1);  
INSERT INTO IsIn VALUES('M6K 1E4', 1);  
INSERT INTO IsIn VALUES('M6J 0A6', 1);  
INSERT INTO IsIn VALUES('M6J 1J4', 1);   -- Toronto
INSERT INTO IsIn VALUES('L5V 2A8', 3);  -- Mississauga
INSERT INTO IsIn VALUES('L5M 4L9', 3);  
INSERT INTO IsIn VALUES('L5M 7E1', 3);  
INSERT INTO IsIn VALUES('L5V 2X8', 3);  
INSERT INTO IsIn VALUES('L5R 3W4', 3);  
INSERT INTO IsIn VALUES('L4Z 3W7', 3);  
INSERT INTO IsIn VALUES('L5R 3E7', 3);  
INSERT INTO IsIn VALUES('L5B 2C9', 3);  
INSERT INTO IsIn VALUES('L4Z 2G5', 3);  
INSERT INTO IsIn VALUES('L5A 2H4', 3);  
INSERT INTO IsIn VALUES('L5A 4C7', 3);  
INSERT INTO IsIn VALUES('L5B 1H9', 3);  
INSERT INTO IsIn VALUES('L5A 2X1', 3);  
INSERT INTO IsIn VALUES('L4Y 2C7', 3);  
INSERT INTO IsIn VALUES('L4W 1M3', 3);  -- Mississauga
INSERT INTO IsIn VALUES('L3R 5W9', 2);   -- Markham
INSERT INTO IsIn VALUES('L3R 2P4', 2);  
INSERT INTO IsIn VALUES('L3R 5P1', 2);  
INSERT INTO IsIn VALUES('L3R 5Y1', 2);  
INSERT INTO IsIn VALUES('L3P 3J3', 2);  
INSERT INTO IsIn VALUES('L3R 4M9', 2); 
INSERT INTO IsIn VALUES('L6C 1Y9', 2);   -- Markham
INSERT INTO IsIn VALUES('L4C 3E3', 4);   -- Richmond Hill
INSERT INTO IsIn VALUES('L4C 3C5', 4);  
INSERT INTO IsIn VALUES('L4C 4Z3', 4);  
INSERT INTO IsIn VALUES('L4C 1V8', 4);  
INSERT INTO IsIn VALUES('L4C 5T2', 4);  
INSERT INTO IsIn VALUES('L4C 7A1', 4);
INSERT INTO IsIn VALUES('L4C 9X4', 4); 
INSERT INTO IsIn VALUES('L4B 1K1', 4);
INSERT INTO IsIn VALUES('L4B 1G7', 4); 
INSERT INTO IsIn VALUES('L4B 3K4', 4);  
INSERT INTO IsIn VALUES('L4S 0A1', 4); -- Richmond Hill